"""empty message

Revision ID: d0f16b437188
Revises: 
Create Date: 2025-07-19 17:19:45.040768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f16b437188'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(255), nullable=False),
    sa.Column('poster', sa.String(500), nullable=False),
    sa.Column('banner', sa.String(500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=225), nullable=True),
    sa.Column('film_subs', sa.JSON(), nullable=True),
    sa.Column('num_watch', sa.Integer(), nullable=True),
    sa.Column('view_movie', sa.JSON(), nullable=True),
    sa.Column('token', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('tags')
    op.drop_table('movies')
    # ### end Alembic commands ###
